### ISSUE TITLE
Release KNI 10.2.0

### ISSUE THREAD

**Issue by folmos-at-orange** [KhiopsML/khiops#153]
#### Description
The release of the Khiops Native Interface (KNI) library has been postponed until we can test it thoroughly.

Also we need to make a packaging workflow for windows.
#### Questions/Ideas
- Add the windows KNI packaging to the NSIS workflow
- How to package the KNITransfer executable to be able to test in the test infrastructure ?

**Comment by bruno-at-orange** [comment]
some information:
- Windows:  originally, the KNI package is a ZIP file. We can  produce a ZIP package _for free_ with cpack : `cpack -G ZIP`. I'm not sure we need to produce an NSIS package.
- Linux : the packaging is done (rpm and deb). Perhaps a link to the documentation is missing (see next point).
- Documentation: the github project [KNI-tutorial](https://github.com/KhiopsML/KNI-tutorial) contains documentation and samples for KNI. It is complete except for the installation part. This project is automatically updated by the action `update-kni-tutorial`. This action updates the scripts in the markdown and creates a tag. For the next release, it has to be referenced somewhere. And the action must be triggered automatically (by a tag creation perhaps).
- KNITransfer: for linux, it is easy to build a new package (it could install KNITransfer in /usr/bin). My only concern was the rpath of KNI in KNITransfer, on the build tree it is an absolute path. In fact, cmake replaces the rpath at the installation time. In order to have the good path we have to add the following in install.cmake: 

```cmake
set_target_properties(KNITransfer PROPERTIES INSTALL_RPATH "/${LIB_DIR}")
install(TARGETS KNITransfer RUNTIME COMPONENT KNI)
```

**Comment by folmos-at-orange** [comment]
- Now standard test KNI in the CI for windows since #
- Packaging of KNITransfer will be treated in #188
