### ISSUE TITLE
Switch to OpenMPI for Linux packages

### ISSUE THREAD

**Issue by bruno-at-orange** [KhiopsML/khiops#203]
OpenMpi seems better than MPICH for multiple reasons (well documented, better packaging etc...). We have to study the best way to switch from MPICH to OpenMPI. Ideally, we should be able to deliver a package for mpich and a package for intelmpi. 
This issue is  related to #164

**Comment by folmos-at-orange** [comment]
If the study is successful the code is compatible OpenMPI, I think we should use it in the conda package as well (and that implies in macOS), since it is more stable.

@bruno-at-orange  If you have a patch (even "beta") with the compatible code for openmpi could you alert `khiops-python` team so we can test the conda packaging?.

**Comment by bruno-at-orange** [comment]
close with:
- #252 on dev 
- #229 on dev-v10
