### ISSUE TITLE
Build macOS conda package

### ISSUE THREAD

**Issue by folmos-at-orange** [KhiopsML/khiops#22]

**Comment by bruno-at-orange** [comment]
First try on the branch 22-. I have a build issue in conda on macos-latest:
>  ld: unsupported tapi file type '!tapi-tbd' in YAML file '/Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd' for architecture x86_64

The issue is documented [here](https://developer.apple.com/forums/thread/722490) ore [here](https://stackoverflow.com/questions/69236331/conda-macos-big-sur-ld-unsupported-tapi-file-type-tapi-tbd-in-yaml-file) without obvious solution.
