### ISSUE TITLE
Conda build fails on windows

### ISSUE THREAD

**Issue by bruno-at-orange** [KhiopsML/khiops#271]
There is an issue with the compiler setting: https://github.com/KhiopsML/khiops/actions/runs/9210331235/job/25337089165#logs

**Comment by folmos-at-orange** [comment]
After some investigation the source of the problem comes from a change in the GitHub runners: https://github.com/actions/runner-images/issues/9701.
In summary, before this change, the runner's VS installation contained many versions of the runtime and build tools. After the change only those of VS 2022 remained. Since conda uses a previous version of the VS runtime the build fails.

I implemented a POC fix in [this branch](/KhiopsML/khiops/fix-windows-build) that largely consists in adding the `vs2022_win-64` package to the conda windows build (see [this workflow run](https://github.com/KhiopsML/khiops/actions/runs/9364166774)). However this impose us the constraint of adding `conda-forge` to the installation process in windows.
Nonetheless, implementing this fix helped me to understand better the problem.

I will try another fix by installing the necessary components in the runner before building the conda package. If this works we should be able to obtain the same package as before (without new dependencies and channels).

**Comment by folmos-at-orange** [comment]
Simply changing the GitHub runner to `windows-2019` fixes the problem.

I tried to install myself VS 2017 in the runner but it did not work. I propose for the moment merging PR #288 because:
- Trying to install VS 2017 correctly is very time consuming
- The `conda-forge` team will soon pass to a more recent VS runtime/build tools (see https://github.com/conda-forge/vc-feedstock/issues/78 and https://github.com/conda-forge/vc-feedstock/issues/71). So we can move to `windows-2022` when this happens.

**Comment by folmos-at-orange** [comment]
Another useful link: List of removed components https://github.com/actions/runner-images/pull/9819/files

**Comment by alexisbondu** [comment]
fixed : #288
